#!/usr/bin/python
# install_crond.py
# write a cron.d job to inject a timestamp to bash history
# Last Edited: 6/8/18 Julian Thies

''' imports '''
import os
import sys
import time
from time import strftime
import getpass

''' variables '''
starDate = strftime("%Y-%m-%d-%H-%M-%S", time.localtime())
userName = getpass.getuser()
binary_loc = sys.argv[1]
usage = 'install_crond.py <binary>'

''' cron.d job '''
line0 = '#   ' + starDate
line1 = '#   Generated by User: ' + userName
line2 = '0 * * * * root ' + binary_loc + '/injectTimeStampBashHist.py'

''' functions '''
def check_binary_loc():
	if not binary_loc:
		print(usage)

def write_crond_job(filename):
	with open(filename, 'a') as f:
		f.write(line0 + os.linesep)
		f.write(line1 + os.linesep)
		f.write(line2 + os.linesep)

''' script '''
write_crond_job('/etc/cron.d/injectTimeStampBashHist')
